//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MujZavod.Admin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ControllerActionNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControllerActionNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MujZavod.Admin.Properties.ControllerActionNames", typeof(ControllerActionNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oprávnění.
        /// </summary>
        public static string Example_Membership {
            get {
                return ResourceManager.GetString("Example_Membership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Překlady.
        /// </summary>
        public static string Example_Translations {
            get {
                return ResourceManager.GetString("Example_Translations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukázky.
        /// </summary>
        public static string Examples {
            get {
                return ResourceManager.GetString("Examples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajax panel.
        /// </summary>
        public static string Examples_AjaxPanel {
            get {
                return ResourceManager.GetString("Examples_AjaxPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Struktura aplikace.
        /// </summary>
        public static string Examples_AppStructure {
            get {
                return ResourceManager.GetString("Examples_AppStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grafy.
        /// </summary>
        public static string Examples_Charts {
            get {
                return ResourceManager.GetString("Examples_Charts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Použité komponenty.
        /// </summary>
        public static string Examples_Components {
            get {
                return ResourceManager.GetString("Examples_Components", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout administrace.
        /// </summary>
        public static string Examples_Layout {
            get {
                return ResourceManager.GetString("Examples_Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oprávnění.
        /// </summary>
        public static string Examples_Membership {
            get {
                return ResourceManager.GetString("Examples_Membership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modální okno.
        /// </summary>
        public static string Examples_Modal {
            get {
                return ResourceManager.GetString("Examples_Modal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastavení.
        /// </summary>
        public static string Examples_Settings {
            get {
                return ResourceManager.GetString("Examples_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabulky +editace v řádku.
        /// </summary>
        public static string Examples_Tables {
            get {
                return ResourceManager.GetString("Examples_Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabulky + vlastní editace.
        /// </summary>
        public static string Examples_TablesCustomCrud {
            get {
                return ResourceManager.GetString("Examples_TablesCustomCrud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Překlady.
        /// </summary>
        public static string Examples_Translations {
            get {
                return ResourceManager.GetString("Examples_Translations", resourceCulture);
            }
        }
    }
}
